# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jiangwei/python/pyqt5-project/PyQt5-QWidgetDemo/44_moneytool/widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(400, 300)
        self.widget = QtWidgets.QWidget(Widget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 86))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.labYears = QtWidgets.QLabel(self.widget)
        self.labYears.setObjectName("labYears")
        self.gridLayout.addWidget(self.labYears, 1, 2, 1, 1)
        self.labMoneyCurrent = QtWidgets.QLabel(self.widget)
        self.labMoneyCurrent.setObjectName("labMoneyCurrent")
        self.gridLayout.addWidget(self.labMoneyCurrent, 0, 0, 1, 1)
        self.txtRate = QtWidgets.QLineEdit(self.widget)
        self.txtRate.setObjectName("txtRate")
        self.gridLayout.addWidget(self.txtRate, 0, 3, 1, 1)
        self.txtMoneyCurrent = QtWidgets.QLineEdit(self.widget)
        self.txtMoneyCurrent.setObjectName("txtMoneyCurrent")
        self.gridLayout.addWidget(self.txtMoneyCurrent, 0, 1, 1, 1)
        self.labRate = QtWidgets.QLabel(self.widget)
        self.labRate.setObjectName("labRate")
        self.gridLayout.addWidget(self.labRate, 0, 2, 1, 1)
        self.labYear = QtWidgets.QLabel(self.widget)
        self.labYear.setObjectName("labYear")
        self.gridLayout.addWidget(self.labYear, 1, 0, 1, 1)
        self.labType = QtWidgets.QLabel(self.widget)
        self.labType.setObjectName("labType")
        self.gridLayout.addWidget(self.labType, 2, 0, 1, 1)
        self.cboxType = QtWidgets.QComboBox(self.widget)
        self.cboxType.setObjectName("cboxType")
        self.cboxType.addItem("")
        self.cboxType.addItem("")
        self.gridLayout.addWidget(self.cboxType, 2, 1, 1, 1)
        self.cboxYear = QtWidgets.QComboBox(self.widget)
        self.cboxYear.setObjectName("cboxYear")
        self.cboxYear.addItem("")
        self.cboxYear.addItem("")
        self.cboxYear.addItem("")
        self.gridLayout.addWidget(self.cboxYear, 1, 1, 1, 1)
        self.txtYears = QtWidgets.QLineEdit(self.widget)
        self.txtYears.setObjectName("txtYears")
        self.gridLayout.addWidget(self.txtYears, 1, 3, 1, 1)
        self.txtMoneyAll = QtWidgets.QLineEdit(self.widget)
        self.txtMoneyAll.setObjectName("txtMoneyAll")
        self.gridLayout.addWidget(self.txtMoneyAll, 2, 3, 1, 1)
        self.labMoneyAll = QtWidgets.QLabel(self.widget)
        self.labMoneyAll.setObjectName("labMoneyAll")
        self.gridLayout.addWidget(self.labMoneyAll, 2, 2, 1, 1)
        self.btnOk = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOk.sizePolicy().hasHeightForWidth())
        self.btnOk.setSizePolicy(sizePolicy)
        self.btnOk.setObjectName("btnOk")
        self.gridLayout.addWidget(self.btnOk, 0, 4, 3, 1)

        self.retranslateUi(Widget)
        self.cboxType.setCurrentIndex(1)
        self.cboxYear.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "存款计算器"))
        self.labYears.setText(_translate("Widget", "年限"))
        self.labMoneyCurrent.setText(_translate("Widget", "本金"))
        self.txtRate.setText(_translate("Widget", "0.04125"))
        self.txtMoneyCurrent.setText(_translate("Widget", "1000000"))
        self.labRate.setText(_translate("Widget", "利率"))
        self.labYear.setText(_translate("Widget", "期限"))
        self.labType.setText(_translate("Widget", "方式"))
        self.cboxType.setItemText(0, _translate("Widget", "单利"))
        self.cboxType.setItemText(1, _translate("Widget", "复利"))
        self.cboxYear.setItemText(0, _translate("Widget", "1年"))
        self.cboxYear.setItemText(1, _translate("Widget", "3年"))
        self.cboxYear.setItemText(2, _translate("Widget", "5年"))
        self.txtYears.setText(_translate("Widget", "30"))
        self.labMoneyAll.setText(_translate("Widget", "总计"))
        self.btnOk.setText(_translate("Widget", "计算"))
