# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jiangwei/python/pyqt5-project/PyQt5-QWidgetDemo/31_screenwidget/frmscreenwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmScreenWidget(object):
    def setupUi(self, frmScreenWidget):
        frmScreenWidget.setObjectName("frmScreenWidget")
        frmScreenWidget.resize(800, 600)
        self.pushButton = QtWidgets.QPushButton(frmScreenWidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 92, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(frmScreenWidget)
        QtCore.QMetaObject.connectSlotsByName(frmScreenWidget)

    def retranslateUi(self, frmScreenWidget):
        _translate = QtCore.QCoreApplication.translate
        frmScreenWidget.setWindowTitle(_translate("frmScreenWidget", "Form"))
        self.pushButton.setText(_translate("frmScreenWidget", "弹出"))
