# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jiangwei/python/pyqt5-project/PyQt5-QWidgetDemo/22_lineeditnext/widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(400, 300)
        self.lineEdit1 = QtWidgets.QLineEdit(Widget)
        self.lineEdit1.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(Widget)
        self.lineEdit2.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit2.setObjectName("lineEdit2")
        self.lineEdit3 = QtWidgets.QLineEdit(Widget)
        self.lineEdit3.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.lineEdit3.setObjectName("lineEdit3")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
